- name: homebrew taps
  command: brew tap {{ item }}
  loop: '{{ homebrew_taps }}'
  tags:
  - brew

- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: true
  tags:
  - brew

- name: Uninstall old homebrew packages
  homebrew:
    name: '{{ item }}'
    state: absent
  with_items: '{{ homebrew_package_removals }}'
  tags:
  - brew

- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'
  tags:
  - brew

- name: Install homebrew cask packages
# TODO: re-enable after homebrew_cask ansible module is fixed
#  community.general.homebrew_cask:
#    name: '{{ item }}'
#    state: installed
  command: brew install --cask {{ item}}
  loop: '{{ homebrew_cask_packages }}'
  tags:
  - brew

- name: homebrew cleanup
  command: brew cleanup

# If pyenv fails, check https://github.com/pyenv/pyenv/wiki/Common-build-problems#build-failed-error-the-python-zlib-extension-was-not-compiled-missing-the-zlib
- name: python versions
  command: pyenv install {{ item }}
  environment:
    CONFIGURE_OPTS: --enable-optimizations
  register: pyenv_install_result
  failed_when: >
    pyenv_install_result.rc != 0 and
    pyenv_install_result.stderr_lines != ["pyenv: /Users/tkuthan/.pyenv/versions/" + item + " already exists"]
  loop: '{{ pyenv_python_versions }}'
  tags:
  - python
  - pyenv

- name: python versions active
  command: pyenv global {{ pyenv_python_versions|join(" ") }}
  tags:
  - python
  - pyenv

- name: python versions shims rehashed
  # Needs running after every update of pyenv, at least, to fix the pyenv shims
  command: pyenv rehash

- name: python versions latest build requirements
  pip:
    name:
    - Cython
    - pep517
    - pip
    - pip-tools
    - setuptools
    - virtualenv
    state: latest
    executable: '~/.pyenv/versions/{{ item }}/bin/pip{% if "pypy3" in item %}3{% endif %}'
  environment:
    PIP_REQUIRE_VIRTUALENV: ""
  loop: '{{ pyenv_python_versions }}'
  tags:
  - python
  - pip
  - pyenv

- name: Install pip packages
  pip:
    name: '{{ pip_packages }}'
    state: latest
    executable: '~/.pyenv/versions/{{ pyenv_python_versions[0] }}/bin/pip'
  environment:
    PIP_REQUIRE_VIRTUALENV: ""
  tags:
  - python
  - pip
  - wheel

- name: Install gem packages
  gem:
    name: '{{ item }}'
    state: latest
  loop: '{{ gem_packages }}'
  tags:
  - gem
